version: '3'

services:
  django_app:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "5001:5001"
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - django_app


